datasource:
  write:
    url: jdbc:mysql://localhost:3306/app?useunicode=true&characterencoding=utf-8
    username: root
    password: root
  read:
    url: jdbc:mysql://localhost:3306/app?useunicode=true&characterencoding=utf-8
    username: root
    password: root
spring:
  redis:
    # redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password: ~
    timeout: 0
logging:
  level.com.ysx: debug




  
  
  
  
  
  
  