server:
  port: 8088
  servlet:
    context-path: /app
spring:
  profiles:
    active: dev
  # springboot 2.0以后可直接配置就可使用
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 2000ms # 最大连接等待时间，-1为无限制
        min-idle: 0
    #host: localhost
    #database: 0
    #port: 6379
    #password:
    #timeout: 5000
    #lettuce: 使用jedis：当多线程使用同一个连接时，是线程不安全的。所以要使用连接池，为每个jedis实例分配一个连接。
    #使用Lettuce：当多线程使用同一连接实例时，是线程安全的。

datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  write:
    driver-class-name: com.mysql.jdbc.Driver
    # 以下为写库连接池参数
    initialSize: 5
    minIdle: 5
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from dual
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j # log4j等
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  read:
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from dual
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
logging:
  file: logs/app.${server.port}.log